apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bt77
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-bt77@sha256:25372164e7bd0c70d618a889abcc7cc26161dbb2230d04fa60c76592353230fa
        name: my-nodejs
        resources: {}
status: {}
